baseurl = "https://ogv-engi.ch/"  # Include trailing slash
title = "OGV Engi"
copyright = "OGV Engi"
# canonifyurls = true
theme = ["github.com/chipzoller/hugo-clarity"]
# theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "de"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS"]

[pagination]
pagerSize = 10
